#!/bin/bash

sizeof() {
  local folder="$1"
  du -hs "$folder" | cut -f1
}

do_gc() {
  local repo="$1"
  local -r before="$(sizeof $repo)"
  git --git-dir="$repo" reflog expire --all --expire=now
  git --git-dir="$repo" gc --aggressive --prune=now --quiet
  test -n "$DEBUG" && echo "$repo $before $(sizeof $repo)"
}

FOLDER="$1"
test -z "$FOLDER" && FOLDER="."
TOTAL_BEFORE="$(sizeof $FOLDER)"

find "$FOLDER" -type d -name '.git' | while read -r repo; do
  do_gc "$repo"
done

echo "$FOLDER $TOTAL_BEFORE $(sizeof $FOLDER)"
